"""init

Revision ID: bb0a0cd461b8
Revises: 
Create Date: 2025-06-02 18:40:22.976239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0a0cd461b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('usage_frequency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('oidc_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('last_completed', sa.DateTime(), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('oidc_id')
    )
    op.create_table('search_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markup_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_case_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_case_id'], ['search_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.oidc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_case_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_case_id', sa.String(), nullable=True),
    sa.Column('search_result_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['search_case_id'], ['search_cases.id'], ),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markup_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_result_id', sa.String(), nullable=True),
    sa.Column('markup_session_id', sa.String(), nullable=True),
    sa.Column('reranked_position', sa.Integer(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['markup_session_id'], ['markup_sessions.id'], ),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markup_results')
    op.drop_table('search_case_results')
    op.drop_table('markup_sessions')
    op.drop_table('search_cases')
    op.drop_table('users')
    op.drop_table('search_results')
    op.drop_table('search_queries')
    # ### end Alembic commands ###
