"""uniq sq field, daily_lim, daily_min usr

Revision ID: 6a6a47dbb7cf
Revises: bb0a0cd461b8
Create Date: 2025-06-09 17:34:59.607375

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a6a47dbb7cf"
down_revision: str | None = "bb0a0cd461b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("search_queries_query_key", "search_queries", ["query"])
    op.add_column("users", sa.Column("daily_minimum", sa.Integer(), server_default=sa.text("20"), nullable=False))
    op.add_column("users", sa.Column("daily_limit", sa.Integer(), server_default=sa.text("500"), nullable=False))
    op.drop_column("users", "daily_quota")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("daily_quota", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("users", "daily_limit")
    op.drop_column("users", "daily_minimum")
    op.drop_constraint("search_queries_query_key", "search_queries", type_="unique")
    # ### end Alembic commands ###
