"""skip markup session

Revision ID: b5198135903c
Revises: 6a6a47dbb7cf
Create Date: 2025-06-10 12:09:45.606574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5198135903c"
down_revision: str | None = "6a6a47dbb7cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "markup_sessions", sa.Column("is_skipped", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column("users", sa.Column("skipped_count", sa.Integer(), server_default=sa.text("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "skipped_count")
    op.drop_column("markup_sessions", "is_skipped")
    # ### end Alembic commands ###
